.\" -*- nroff -*-
.ig
Documentation for the Image Composition Engine for Tiles (ICE-T).

Copyright (C) 2000-2003 Sandia National Laboratories

Id
..
.TH icetTemplate 3 "May 19, 2003" "Sandia National Labs" "ICE-T Reference"
.SH NAME
.B icetTemplate
\- template for ICE-T man pages
.SH SYNOPSIS
.nf
.B #include <GL/ice-t.h>
.sp
.BI "void icetTemplate(IceTColorBuffer " cb ", IceTDepthBuffer " db ");"
.fi
.SH DESCRIPTION
The
.B icetTemplate
function does not really exist.  I made it up.  You won't find it in
.B GL/ice-t.h
so don't look.  Don't try to use it or your program will not compile or
link.
.PP
Here is a list of other functions that do not exist.
.TP 8	\" Setting indent here sets for subsequent indents.
.B icetNon
If less is more, then this function is everything since it is, in fact,
nothing.
.TP
.B icetRubberBiscuit
What do you want for nothing?
.PP
And that's that.  Nothing more to say, really.
.SH RETURN VALUE
Don't you see the
.BR void ?
.SH ERRORS
.TP 20
.B ICET_INVALID_VALUE
You've screwed something up a little bit.
.TP
.B ICET_INVALID_OPERATION
You've screwed something up a lot.
.TP
.B ICET_OUT_OF_MEMORY
You need a better computer to do what you want to do.
.TP
.B ICET_BAD_CAST
The argument is of the wrong format.
.TP
.B ICET_INVALID_ENUM
One of us does not know what he is talking about.
.TP
.B ICET_SANITY_CHECK_FAIL
I've screwed something up a lot.
.SH WARNINGS
.TP 20
.B ICET_INVALID_VALUE
You've screwed something up a little bit.
.TP
.B ICET_INVALID_OPERATION
You've screwed something up a lot.
.TP
.B ICET_OUT_OF_MEMORY
You need a better computer to do what you want to do.
.TP
.B ICET_BAD_CAST
The argument is of the wrong format.
.TP
.B ICET_INVALID_ENUM
One of us does not know what he is talking about.
.TP
.B ICET_SANITY_CHECK_FAIL
I've screwed something up a lot.
.SH BUGS
None known.
.SH NOTES
This man page should never be installed.  It should just be used to help
make other man pages.
.SH COPYRIGHT
Copyright \(co 2003 Sandia Corporation
.br
Under the terms of Contract DE-AC04-94AL85000, there is a non-exclusive
license for use of this work by or on behalf of the U.S. Government.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that this Notice and any statement of
authorship are reproduced on all copies.
.SH SEE ALSO
.BR icetNon ", " icetRubberBiscuit


\" These are emacs settings that go at the end of the file.
\" Local Variables:
\" writestamp-format:"%B %e, %Y"
\" writestamp-prefix:"3 \""
\" writestamp-suffix:"\" \"Sandia National Labs\""
\" End:
