.\" -*- nroff -*-
.ig
Documentation for the Image Composition Engine for Tiles (ICE-T).

Copyright (C) 2000-2002 Sandia National Laboratories

Id
..
.TH icetGetStrategyName 3 "June 11, 2003" "Sandia National Labs" "ICE-T Reference"
.SH NAME
.B icetGetStrategyName
\- retrieve strategy name.
.SH SYNOPSIS
.nf
.B #include <GL/ice-t.h>
.sp
.BI "const GLubyte icetGetStrategyName(void);"
.fi
.SH RETURN VALUE
Returns a short, null terminated string identifying the strategy currently
in effect.  Helpful for printing out debugging or diagnostic statements.
If no strategy is set, NULL is returned.
.SH ERRORS
None.
.SH WARNINGS
None.
.SH BUGS
None known.
.SH NOTES
The string returned does
.I not
contain the identifier used in a C program.  For example, if the current
strategy is
.BR ICET_STRATEGY_REDUCE ", " icetGetStrategyName
returns `Reduce,' not `ICET_STRATEGY_REDUCE.'
.SH COPYRIGHT
Copyright \(co 2003 Sandia Corporation
.br
Under the terms of Contract DE-AC04-94AL85000, there is a non-exclusive
license for use of this work by or on behalf of the U.S. Government.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that this Notice and any statement of
authorship are reproduced on all copies.
.SH SEE ALSO
.BR icetStrategy


\" These are emacs settings that go at the end of the file.
\" Local Variables:
\" writestamp-format:"%B %e, %Y"
\" writestamp-prefix:"3 \""
\" writestamp-suffix:"\" \"Sandia National Labs\""
\" End:
