.\" -*- nroff -*-
.ig
Documentation for the Image Composition Engine for Tiles (ICE-T).

Copyright (C) 2000-2002 Sandia National Laboratories

Id
..
.TH icetIsEnabled 3 "March 12, 2003" "Sandia National Labs" "ICE-T Reference"
.SH NAME
.B icetIsEnabled
\- query enabled status of an
.B ICE-T
feature.
.SH SYNOPSIS
.nf
.B #include <GL/ice-t.h>
.sp
.BI "GLboolean icetIsEnabled(GLenum " pname ");"
.fi
.SH RETURN VALUE
Returns
.B ICET_TRUE
if the feature associated with
.I pname
is enabled,
.B ICET_FALSE
(= 0) if the feature is disabled.
.SH ERRORS
.TP 20
.B ICET_INVALID_VALUE
If
.I pname
is not a feature to be enabled or disabled.
.SH WARNINGS
None.
.SH BUGS
The check for a valid
.I pname
is not thorough, and thus the
.B ICET_INVALID_VALUE
error may not always be raised.
.SH NOTES
A list of valid values for
.I pname
is given in the documentation for
.BR icetEnable .
.SH COPYRIGHT
Copyright \(co 2003 Sandia Corporation
.br
Under the terms of Contract DE-AC04-94AL85000, there is a non-exclusive
license for use of this work by or on behalf of the U.S. Government.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that this Notice and any statement of
authorship are reproduced on all copies.
.SH SEE ALSO
.BR icetEnable


\" These are emacs settings that go at the end of the file.
\" Local Variables:
\" writestamp-format:"%B %e, %Y"
\" writestamp-prefix:"3 \""
\" writestamp-suffix:"\" \"Sandia National Labs\""
\" End:
